import type { ActionRegistry } from "$lib/app/action_registry/action_registry";
import type { AppMountConfig, VaultService } from "$lib/features/vault";
import type { NoteService } from "$lib/features/note";
import type { FolderService } from "$lib/features/folder";
import type { SettingsService } from "$lib/features/settings";
import type { SearchService } from "$lib/features/search";
import type { EditorService } from "$lib/features/editor";
import type { ClipboardService } from "$lib/features/clipboard";
import type { ShellService } from "$lib/features/shell";
import type { TabService } from "$lib/features/tab";
import type { GitService } from "$lib/features/git";
import type { HotkeyService } from "$lib/features/hotkey";
import type { ThemeService } from "$lib/features/theme";
import type { UIStore } from "$lib/app/orchestration/ui_store.svelte";
import type { VaultStore } from "$lib/features/vault";
import type { NotesStore } from "$lib/features/note";
import type { EditorStore } from "$lib/features/editor";
import type { OpStore } from "$lib/app/orchestration/op_store.svelte";
import type { SearchStore } from "$lib/features/search";
import type { TabStore } from "$lib/features/tab";
import type { GitStore } from "$lib/features/git";
import type { OutlineStore } from "$lib/features/outline";
import type { GraphStore } from "$lib/features/graph";
import type { BasesStore } from "$lib/features/bases";
import type { TaskStore } from "$lib/features/task";
import type { SttStore } from "$lib/features/stt";
import type { ParsedNoteCache } from "$lib/features/note";
import type { WorkspaceReconcile } from "$lib/app/orchestration/workspace_reconcile";
import type { ReferenceStore } from "$lib/features/reference";
import type { ReferenceService } from "$lib/features/reference";
import type { DocumentService } from "$lib/features/document";

export type ActionRegistrationInput = {
  registry: ActionRegistry;
  workspace_reconcile?: WorkspaceReconcile | undefined;
  stores: {
    ui: UIStore;
    vault: VaultStore;
    notes: NotesStore;
    editor: EditorStore;
    op: OpStore;
    search: SearchStore;
    tab: TabStore;
    git: GitStore;
    outline: OutlineStore;
    graph: GraphStore;
    bases: BasesStore;
    task: TaskStore;
    stt: SttStore;
    parsed_note_cache: ParsedNoteCache;
    reference: ReferenceStore;
  };
  services: {
    vault: VaultService;
    note: NoteService;
    folder: FolderService;
    settings: SettingsService;
    search: SearchService;
    editor: EditorService;
    clipboard: ClipboardService;
    shell: ShellService;
    tab: TabService;
    git: GitService;
    hotkey: HotkeyService;
    theme: ThemeService;
    reference: ReferenceService;
    document: DocumentService;
  };
  default_mount_config: AppMountConfig;
};
