import { SvelteMap } from "svelte/reactivity";

// PHASE 3: ParsedNoteDto no longer generated by Rust backend.
// Cache retained for DI compatibility; will be repurposed or removed in Phase 7.
type ParsedNoteDto = Record<string, unknown>;

export class ParsedNoteCache {
  private cache = new SvelteMap<string, ParsedNoteDto>();

  set(file_path: string, parsed: ParsedNoteDto): void {
    this.cache.set(file_path, parsed);
  }

  get(file_path: string): ParsedNoteDto | undefined {
    return this.cache.get(file_path);
  }

  invalidate(file_path: string): void {
    this.cache.delete(file_path);
  }

  clear(): void {
    this.cache.clear();
  }
}
