import type { EditorSettings } from "$lib/shared/types/editor_settings";

export type SettingDefinition = {
  key: keyof EditorSettings;
  label: string;
  description: string;
  category: string;
  keywords: string[];
};

export const SETTINGS_REGISTRY: SettingDefinition[] = [
  {
    key: "default_note_name_template",
    label: "Default Note Name",
    description:
      "Template for new note names using strftime tokens: %Y (year), %m (month), %d (day), %H (hour), %M (minute), %S (second). Leave empty for Untitled-N.",
    category: "Files",
    keywords: [
      "name",
      "template",
      "date",
      "daily",
      "zettelkasten",
      "strftime",
      "default",
      "naming",
    ],
  },
  {
    key: "attachment_folder",
    label: "Attachment Folder",
    description: "Folder name for storing pasted images and attachments",
    category: "Files",
    keywords: [
      "assets",
      "images",
      "attachments",
      "folder",
      "path",
      "upload",
      "paste",
    ],
  },
  {
    key: "ignored_folders",
    label: "Ignored Folders",
    description:
      "Vault-relative folders to exclude from the tree and indexing, in addition to .vaultignore and .gitignore",
    category: "Files",
    keywords: [
      "ignore",
      "ignored",
      "vaultignore",
      "gitignore",
      "folder",
      "exclude",
      "skip",
    ],
  },
  {
    key: "show_hidden_files",
    label: "Show Hidden Files",
    description: "Show dot-prefixed files and folders in the file tree",
    category: "Files",
    keywords: [
      "hidden",
      "dot",
      "dotfiles",
      "dotfolders",
      "invisible",
      "show",
      "hide",
    ],
  },
  {
    key: "autosave_enabled",
    label: "Autosave",
    description: "Automatically save markdown notes after edits",
    category: "Files",
    keywords: [
      "autosave",
      "auto save",
      "save",
      "automatic",
      "draft",
      "unsaved",
    ],
  },
  {
    key: "autosave_delay_ms",
    label: "Autosave Delay",
    description:
      "Delay in milliseconds before automatically saving after edits",
    category: "Files",
    keywords: [
      "autosave",
      "delay",
      "time",
      "save",
      "automatic",
      "performance",
      "interval",
    ],
  },
  {
    key: "git_autocommit_mode",
    label: "Auto-commit Mode",
    description: "When to automatically commit saved changes to Git",
    category: "Git",
    keywords: [
      "git",
      "autocommit",
      "auto commit",
      "commit",
      "version",
      "automatic",
      "mode",
    ],
  },
  {
    key: "git_autocommit_interval_minutes",
    label: "Auto-commit Interval",
    description: "Minutes between automatic commits (when using interval mode)",
    category: "Git",
    keywords: [
      "git",
      "autocommit",
      "interval",
      "minutes",
      "timer",
      "frequency",
    ],
  },
  {
    key: "git_pull_strategy",
    label: "Pull Strategy",
    description:
      "How Git pull integrates remote changes into the current branch",
    category: "Git",
    keywords: ["git", "pull", "merge", "rebase", "ff-only", "strategy"],
  },
  {
    key: "git_auto_fetch_interval_minutes",
    label: "Auto-fetch Interval",
    description: "How often to refresh remote status in the background",
    category: "Git",
    keywords: [
      "git",
      "fetch",
      "remote",
      "interval",
      "minutes",
      "background",
      "poll",
    ],
  },
  {
    key: "show_vault_dashboard_on_open",
    label: "Show Vault Dashboard on Open",
    description: "Open vault dashboard automatically when switching vaults",
    category: "Misc",
    keywords: ["vault", "dashboard", "overview", "open", "startup", "switch"],
  },
  {
    key: "lint_enabled",
    label: "Enable Markdown Linting",
    description:
      "Run rumdl in the background to check markdown files for style and formatting issues",
    category: "Tools",
    keywords: [
      "lint",
      "markdown",
      "rumdl",
      "check",
      "style",
      "format",
      "diagnostics",
    ],
  },
  {
    key: "lint_format_on_save",
    label: "Format on Save",
    description: "Automatically format the current markdown file when saving",
    category: "Tools",
    keywords: ["lint", "format", "save", "auto", "markdown", "prettier"],
  },
  {
    key: "lint_formatter",
    label: "Formatter",
    description:
      "Which tool to use for markdown formatting. Prettier is recommended for most users",
    category: "Tools",
    keywords: ["lint", "formatter", "format", "prettier", "rumdl", "markdown"],
  },
  {
    key: "lint_rules_toml",
    label: "Rule Overrides (TOML)",
    description:
      "Custom rumdl rule configuration in TOML format, merged with defaults. Example: MD013 = false",
    category: "Tools",
    keywords: [
      "lint",
      "rules",
      "toml",
      "config",
      "rumdl",
      "override",
      "custom",
    ],
  },
  {
    key: "rumdl_binary_path",
    label: "rumdl Binary Path",
    description:
      "Path to the rumdl binary. Leave empty to use the bundled version",
    category: "Tools",
    keywords: ["rumdl", "lint", "binary", "path", "executable", "markdown"],
  },
  {
    key: "file_tree_style",
    label: "File Tree Style",
    description:
      "Visual style for the file explorer sidebar: default, airy_minimal, compact, macos_finder, or refined",
    category: "Layout",
    keywords: [
      "file",
      "tree",
      "explorer",
      "sidebar",
      "style",
      "minimal",
      "airy",
      "compact",
      "finder",
      "macos",
      "refined",
      "vscode",
      "appearance",
    ],
  },
  {
    key: "file_tree_show_blurb",
    label: "Show File Blurb",
    description:
      "Display a secondary line on file tree rows with a note description or preview",
    category: "Layout",
    keywords: [
      "file",
      "tree",
      "blurb",
      "description",
      "preview",
      "caption",
      "subtitle",
      "two-line",
    ],
  },
  {
    key: "file_tree_blurb_position",
    label: "Blurb Position",
    description:
      "Whether the blurb appears as a caption below the filename or as the heading above it",
    category: "Layout",
    keywords: [
      "file",
      "tree",
      "blurb",
      "position",
      "caption",
      "heading",
      "layout",
    ],
  },
  {
    key: "max_open_tabs",
    label: "Max Open Tabs",
    description: "Maximum number of tabs that can be open at once",
    category: "Layout",
    keywords: ["tabs", "limit", "max", "open", "performance", "editor"],
  },
  {
    key: "editor_max_width_ch",
    label: "Editor Max Width",
    description: "Maximum line width for the editor content in characters",
    category: "Layout",
    keywords: ["editor", "width", "line length", "layout", "readability"],
  },
  {
    key: "editor_selection_color",
    label: "Selection Color",
    description: "Override the editor selection highlight color",
    category: "Layout",
    keywords: ["editor", "selection", "highlight", "color", "appearance"],
  },
  {
    key: "editor_heading_spacing_density",
    label: "Heading Spacing",
    description: "Controls vertical spacing around headings in the editor",
    category: "Layout",
    keywords: ["editor", "heading", "spacing", "density", "readability"],
  },
  {
    key: "editor_paragraph_spacing_density",
    label: "Paragraph Spacing",
    description: "Controls paragraph spacing density in the editor",
    category: "Layout",
    keywords: ["editor", "paragraph", "spacing", "density", "readability"],
  },
  {
    key: "editor_list_spacing_density",
    label: "List Spacing",
    description: "Controls list spacing density in the editor",
    category: "Layout",
    keywords: ["editor", "list", "spacing", "density", "readability"],
  },
  {
    key: "editor_code_block_padding",
    label: "Code Block Padding",
    description: "Controls padding inside editor code blocks",
    category: "Layout",
    keywords: ["editor", "code", "block", "padding", "appearance"],
  },
  {
    key: "editor_code_block_radius",
    label: "Code Block Radius",
    description: "Controls corner radius for editor code blocks",
    category: "Layout",
    keywords: ["editor", "code", "block", "radius", "appearance"],
  },
  {
    key: "editor_code_block_wrap",
    label: "Code Block Wrap",
    description: "Wrap long lines in code blocks instead of horizontal scroll",
    category: "Layout",
    keywords: ["editor", "code", "block", "wrap", "scroll", "overflow"],
  },
  {
    key: "source_editor_line_numbers",
    label: "Source Editor Line Numbers",
    description: "Show line numbers in the source editor gutter",
    category: "Layout",
    keywords: ["editor", "source", "line", "numbers", "gutter"],
  },
  {
    key: "editor_toolbar_visibility",
    label: "Toolbar Visibility",
    description:
      "Controls when the formatting toolbar appears: on text selection, always visible, or hidden",
    category: "Layout",
    keywords: [
      "toolbar",
      "formatting",
      "visibility",
      "floating",
      "sticky",
      "hide",
      "show",
      "selection",
    ],
  },
  {
    key: "editor_heading_markers",
    label: "Heading Markers",
    description:
      "Show markdown heading level markers (e.g. ##) before headings in the visual editor",
    category: "Layout",
    keywords: [
      "heading",
      "marker",
      "hash",
      "source",
      "pseudo",
      "level",
      "obsidian",
      "visual",
    ],
  },
  {
    key: "editor_block_drag_handle",
    label: "Block Drag Handle",
    description:
      "Show a drag handle in the left gutter to reorder blocks by dragging",
    category: "Layout",
    keywords: ["drag", "handle", "block", "reorder", "move", "grip", "gutter"],
  },
  {
    key: "editor_block_drag_handle_visibility",
    label: "Block Drag Handle Visibility",
    description:
      "Control when the block drag handle is visible: on hover or always",
    category: "Layout",
    keywords: ["drag", "handle", "visibility", "hover", "always", "show"],
  },
  {
    key: "editor_spellcheck",
    label: "Spell Check",
    description: "Enable browser-native spell checking in the editor",
    category: "Layout",
    keywords: [
      "spell",
      "spellcheck",
      "spelling",
      "check",
      "grammar",
      "typo",
      "editor",
    ],
  },
  {
    key: "editor_table_spacing_density",
    label: "Table Spacing",
    description: "Controls cell padding and density in editor tables",
    category: "Layout",
    keywords: ["editor", "table", "spacing", "density", "padding", "cell"],
  },
  {
    key: "editor_blockquote_padding",
    label: "Blockquote Padding",
    description: "Controls padding inside editor blockquotes",
    category: "Layout",
    keywords: ["editor", "blockquote", "quote", "padding", "appearance"],
  },
  {
    key: "editor_blockquote_border_width",
    label: "Blockquote Border Width",
    description: "Controls the border width used for editor blockquotes",
    category: "Layout",
    keywords: ["editor", "blockquote", "quote", "border", "width"],
  },
  {
    key: "editor_link_underline_style",
    label: "Link Underline Style",
    description: "Controls how links are underlined in the editor",
    category: "Layout",
    keywords: ["editor", "link", "underline", "style", "appearance"],
  },
  {
    key: "editor_divider_style",
    label: "Divider Style",
    description: "Controls how horizontal rules are displayed in the editor",
    category: "Layout",
    keywords: [
      "editor",
      "divider",
      "horizontal",
      "rule",
      "hr",
      "separator",
      "line",
      "style",
    ],
  },
  {
    key: "terminal_shell_path",
    label: "Shell Path",
    description: "Path to the shell executable used by the terminal",
    category: "Terminal",
    keywords: ["terminal", "shell", "zsh", "bash", "path", "command", "pty"],
  },
  {
    key: "terminal_font_size_px",
    label: "Terminal Font Size",
    description: "Font size used by the embedded terminal",
    category: "Terminal",
    keywords: ["terminal", "font", "size", "text", "xterm"],
  },
  {
    key: "terminal_cursor_blink",
    label: "Terminal Cursor Blink",
    description: "Animate the terminal cursor while focused",
    category: "Terminal",
    keywords: ["terminal", "cursor", "blink", "caret"],
  },
  {
    key: "terminal_follow_active_vault",
    label: "Follow Active Vault",
    description:
      "Respawn the terminal in the active vault when switching vaults",
    category: "Terminal",
    keywords: ["terminal", "vault", "cwd", "working directory", "follow"],
  },
  {
    key: "terminal_font_family",
    label: "Terminal Font Family",
    description:
      "Font family for the terminal. Leave empty for the system monospace default",
    category: "Terminal",
    keywords: ["terminal", "font", "family", "monospace", "typeface"],
  },
  {
    key: "terminal_font_weight",
    label: "Terminal Font Weight",
    description: "Font weight for normal text in the terminal",
    category: "Terminal",
    keywords: ["terminal", "font", "weight", "normal", "thin"],
  },
  {
    key: "terminal_font_weight_bold",
    label: "Terminal Bold Weight",
    description: "Font weight used for bold text in the terminal",
    category: "Terminal",
    keywords: ["terminal", "font", "weight", "bold"],
  },
  {
    key: "terminal_line_height",
    label: "Terminal Line Height",
    description: "Line height multiplier for the terminal",
    category: "Terminal",
    keywords: ["terminal", "line", "height", "spacing"],
  },
  {
    key: "terminal_cursor_style",
    label: "Terminal Cursor Style",
    description: "Shape of the terminal cursor",
    category: "Terminal",
    keywords: ["terminal", "cursor", "style", "block", "underline", "bar"],
  },
  {
    key: "terminal_scrollback",
    label: "Terminal Scrollback",
    description: "Number of lines retained in the terminal scrollback buffer",
    category: "Terminal",
    keywords: ["terminal", "scrollback", "buffer", "history", "lines"],
  },
  {
    key: "ai_enabled",
    label: "Enable AI",
    description: "Show AI tools and allow local AI assistant execution",
    category: "AI",
    keywords: ["ai", "assistant", "enable", "disable", "llm", "toggle"],
  },
  {
    key: "ai_providers",
    label: "AI Providers",
    description: "Configured AI CLI providers and their commands",
    category: "AI",
    keywords: [
      "ai",
      "provider",
      "backend",
      "cli",
      "command",
      "ollama",
      "claude",
      "codex",
      "lms",
    ],
  },
  {
    key: "ai_default_provider_id",
    label: "Default Provider",
    description:
      "Provider used when opening AI assistant. Auto picks the first available CLI.",
    category: "AI",
    keywords: ["ai", "assistant", "backend", "provider", "default", "auto"],
  },
  {
    key: "ai_execution_timeout_seconds",
    label: "AI Timeout",
    description: "Maximum time to wait for an AI CLI response",
    category: "AI",
    keywords: ["ai", "timeout", "seconds", "duration", "cli"],
  },
  {
    key: "document_pdf_default_zoom",
    label: "PDF Default Zoom",
    description: "Initial zoom mode when opening PDFs",
    category: "Documents",
    keywords: ["pdf", "zoom", "fit width", "documents", "viewer"],
  },
  {
    key: "document_pdf_scroll_mode",
    label: "PDF Scroll Mode",
    description: "Continuous scrolling or single-page navigation for PDFs",
    category: "Documents",
    keywords: [
      "pdf",
      "scroll",
      "continuous",
      "paginated",
      "page",
      "documents",
      "viewer",
    ],
  },
  {
    key: "document_code_wrap",
    label: "Wrap Code/Text Documents",
    description: "Wrap long lines in code and plain-text viewers",
    category: "Documents",
    keywords: ["documents", "viewer", "code", "text", "wrap", "line wrap"],
  },
  {
    key: "document_image_background",
    label: "Image Background",
    description: "Background style behind images in the document viewer",
    category: "Documents",
    keywords: ["documents", "image", "background", "checkerboard", "viewer"],
  },
  {
    key: "document_inactive_cache_limit",
    label: "Inactive Document Cache",
    description: "How many inactive document payloads stay cached",
    category: "Documents",
    keywords: ["documents", "cache", "inactive", "performance", "memory"],
  },
  {
    key: "semantic_similarity_threshold",
    label: "Similarity Threshold",
    description:
      "Minimum similarity (0–1) for suggested links and graph edges. Lower values show more connections.",
    category: "Semantic",
    keywords: ["semantic", "similarity", "threshold", "distance", "embedding"],
  },
  {
    key: "semantic_suggested_links_limit",
    label: "Suggested Links Limit",
    description:
      "Maximum number of suggested wiki-links shown in the links panel",
    category: "Semantic",
    keywords: ["suggested", "links", "limit", "prediction"],
  },
  {
    key: "semantic_graph_edges_per_note",
    label: "Graph Edges per Note",
    description:
      "How many semantic neighbors to find per note when computing graph edges",
    category: "Semantic",
    keywords: ["graph", "edges", "knn", "neighbors", "semantic"],
  },
  {
    key: "semantic_graph_max_vault_size",
    label: "Graph Max Vault Size",
    description:
      "Semantic graph edges are disabled for vaults larger than this (performance)",
    category: "Semantic",
    keywords: ["graph", "vault", "size", "limit", "performance"],
  },
  {
    key: "semantic_omnibar_fallback_enabled",
    label: "Omnibar Semantic Fallback",
    description:
      "Fall back to semantic search when keyword search returns few results",
    category: "Semantic",
    keywords: ["omnibar", "fallback", "hybrid", "search", "semantic"],
  },
  {
    key: "semantic_omnibar_min_words",
    label: "Omnibar Min Words",
    description: "Minimum query word count to trigger semantic fallback",
    category: "Semantic",
    keywords: ["omnibar", "words", "minimum", "fallback", "threshold"],
  },
  {
    key: "graph_force_link_distance",
    label: "Link Distance",
    description:
      "Target distance between connected nodes (higher = more spread)",
    category: "Graph",
    keywords: ["graph", "force", "layout", "spacing", "link", "distance"],
  },
  {
    key: "graph_force_charge_strength",
    label: "Repulsion Strength",
    description:
      "How strongly nodes push apart (more negative = more repulsion)",
    category: "Graph",
    keywords: ["graph", "force", "layout", "spacing", "charge", "repulsion"],
  },
  {
    key: "graph_force_collision_radius",
    label: "Collision Radius",
    description: "Minimum distance between node centers",
    category: "Graph",
    keywords: ["graph", "force", "layout", "spacing", "collision", "radius"],
  },
  {
    key: "graph_force_charge_max_distance",
    label: "Repulsion Range",
    description: "Maximum distance for repulsion force to act",
    category: "Graph",
    keywords: [
      "graph",
      "force",
      "layout",
      "spacing",
      "charge",
      "range",
      "distance",
    ],
  },
  {
    key: "markdown_lsp_enabled",
    label: "Enable Markdown LSP",
    description:
      "Enable the markdown language server for wiki-link completion, go-to-definition, hover, and diagnostics",
    category: "Tools",
    keywords: [
      "markdown_lsp",
      "lsp",
      "language",
      "server",
      "markdown",
      "completion",
      "diagnostics",
    ],
  },
  {
    key: "markdown_lsp_provider",
    label: "Markdown LSP Provider",
    description:
      "Choose the language server for markdown files. IWE provides graph transformations (extract, inline, restructure). Marksman provides standard markdown LSP features.",
    category: "Tools",
    keywords: [
      "markdown",
      "lsp",
      "provider",
      "iwes",
      "iwe",
      "marksman",
      "language",
      "server",
    ],
  },
  {
    key: "markdown_lsp_binary_path",
    label: "Markdown LSP Binary Path",
    description:
      "Custom path to the LSP binary. Leave empty to auto-detect from PATH or toolchain",
    category: "Tools",
    keywords: ["marksman", "iwes", "lsp", "binary", "path", "executable"],
  },
  {
    key: "reference_enabled",
    label: "Enable References",
    description:
      "Enable the reference manager for citing papers, books, and articles in your notes",
    category: "Tools",
    keywords: [
      "reference",
      "citation",
      "zotero",
      "bibliography",
      "academic",
      "papers",
      "doi",
    ],
  },
  {
    key: "reference_citation_style",
    label: "Citation Style",
    description:
      "Default CSL citation style for rendering bibliographies (e.g. apa, vancouver, harvard1)",
    category: "Tools",
    keywords: [
      "reference",
      "citation",
      "style",
      "csl",
      "apa",
      "vancouver",
      "harvard",
      "bibliography",
    ],
  },
  {
    key: "reference_include_sources_in_search",
    label: "Include Sources in Search",
    description:
      "Include linked reference sources (PDFs, HTML) in search results, semantic similarity, and graph edges",
    category: "Tools",
    keywords: ["reference", "search", "linked", "sources", "pdf", "semantic"],
  },
  {
    key: "vim_nav_enabled",
    label: "Vim-Style Navigation",
    description:
      "Use vim keybindings (hjkl, gg, G) for navigating the file tree, tabs, and outline panels",
    category: "Navigation",
    keywords: ["vim", "navigation", "keyboard", "keybinding", "hjkl", "modal"],
  },
  {
    key: "embedding_note_enabled",
    label: "Note Embedding",
    description:
      "Generate embeddings for entire notes (used by semantic search and suggested links)",
    category: "Semantic",
    keywords: [
      "embedding",
      "note",
      "semantic",
      "disable",
      "enable",
      "performance",
      "battery",
    ],
  },
  {
    key: "embedding_block_enabled",
    label: "Block Embedding",
    description:
      "Generate embeddings for individual note sections (used by block-level semantic search)",
    category: "Semantic",
    keywords: [
      "embedding",
      "block",
      "section",
      "semantic",
      "disable",
      "enable",
      "performance",
      "battery",
    ],
  },
];
